version: 2.1.0.{build}
image: Visual Studio 2017
environment:
  $msbuildPath: $(cmd /c where msbuild)
  COVERALLS_REPO_TOKEN: 6Q3DHopayUJ6xtDuAXO9S9Q8GknjKpYUe

configuration: Release

build_script:
  - ps: .\build.ps1 -Target CiBuild -Experimental
  
test: off

artifacts:
  - path: '**\boleto*.nupkg'
    name: nuget

deploy:
- provider: NuGet
  server: https://www.myget.org/F/boleto2netbuild/
  api_key:
    secure: rH9VFKFXJsR5D07BF9PayFm7mRo7acVANtfgYkGa3S9ybX0RCWBiSM153yhLaorG
  skip_symbols: true
  on:
    branch: master
    
notifications:
- provider: Email
  to:
  - cds@cds-software.com.br
  subject: Boleto2Net Build
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: true
